### ISSUE TITLE
Null safety Issue

### ISSUE THREAD

**Issue by hanmadrin** [jogboms/flutter_spinkit#100]
**Describe the bug**
(I am a noob)!
I am building an app and it says this package doesn't support null safety

**Screenshots**
![image](https://user-images.githubusercontent.com/52458243/127672696-5003822d-a144-483f-baad-0841a3e247e1.png)

**Comment by hanmadrin** [comment]
![image](https://user-images.githubusercontent.com/52458243/127672902-73bd9ecb-b98e-4cec-8a9e-8a18ac2f57de.png)

**Comment by LeonardoRosaa** [comment]
Please, try use: 
```yml 
flutter_spinkit: ^5.0.0
```

**Comment by Sarat-1997** [comment]
@LeonardoRosaa  It works!!. Thanks.
