### ISSUE TITLE
WaveSpinner is not working

### ISSUE THREAD

**Issue by buckyroid** [jogboms/flutter_spinkit#109]
**Describe the bug**
Hi, I really like your library, I think it is beautiful and very useful. However, I am having some trouble with SpinKitWaveSpinner class. It is not visible on vscode suggestions and I can't go to definition of the class. It looks like this class doesn't exist. (I tried exporting it in flutter_spinkit.dart but problem still exists.) Maybe you forget to publish it? (I am using version 5.1.0) Can you take a look? Thanks in advance.

**SpinKit name**
SpinKitWaveSpinner

**Comment by jogboms** [comment]
Thanks, it took a while but was released in [v5.2.0](https://github.com/jogboms/flutter_spinkit/releases/tag/v5.2.0)
