### ISSUE TITLE
Symbol Off Center

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [jogboms/flutter_spinkit#29]
Hi, it appears that the loading animation is off-center, making it difficult to align it properly.
<img width="640" alt="imageoffcenter" src="https://user-images.githubusercontent.com/23037821/42357209-9f950c28-808b-11e8-87cb-fd3555a50426.png">

**Comment by jogboms** [comment]
Oh!
I'd investigate this, i thought i fixed it already.

**Comment by jogboms** [comment]
@ThinkDigitalRepair what animation is this?

**Comment by ThinkDigitalSoftware** [comment]
@jogboms it's the fading cube I believe

**Comment by aagarwal1012** [comment]
@ThinkDigitalRepair can you provide the `code snippet` ? 
I seems that this issue doesn't exist.

**Comment by ThinkDigitalSoftware** [comment]
Sure, so you can [get the gist...](https://gist.github.com/ThinkDigitalRepair/05fc3ef931dc297f8cd2bdcbff6e6155)

**Comment by aagarwal1012** [comment]
@ThinkDigitalRepair 
Main reason of this misalignment is that in your code `SpinKitFadingCube(color: Colors.white, width: 40.0)` you are not providing the value of attribute `height` as its default value is `50.0`,  so you set height to 40.0 . By doing so I think that your problem will get resolved.

**Comment by ThinkDigitalSoftware** [comment]
It should still be centered though, right? With a width of 40, the center
should be 20, the vertical measurement shouldn't affect the horizontal
placement, I don't think.

**Comment by ThinkDigitalSoftware** [comment]
I changed it and I did work, but shouldn't it always center the animation? Especially since the height and width aren't required parameters and you don't include an alignment option, it seems like centered should always be true.
Because if I have a container that's 50px wide and 30px tall, it should be centered on 25px unless I set an offset

**Comment by aagarwal1012** [comment]
@jogboms hope you can come back to this issue.

**Comment by jogboms** [comment]
True @ThinkDigitalRepair 

@aagarwal1012 do you think we should refactor some loaders which by default should be a square to take a singular `size` (maybe of type Size) parameter instead of a `width` and `height`?

**Comment by ThinkDigitalSoftware** [comment]
@jogboms I agree with the square. Wouldn't a `double` work since an `Icon` takes a size of type `double`?

**Comment by aagarwal1012** [comment]
@jogboms Totally agreed with that point :+1:

**Comment by jogboms** [comment]
Yeah. @ThinkDigitalRepair. A `double` would do. This would be a major update.

**Comment by ThinkDigitalSoftware** [comment]
No worries, keeping the dimensions square works for me in the meantime.

**Comment by jogboms** [comment]
That leap took barely 3 days @aagarwal1012

**Comment by ershat-dl** [comment]
hi man, try wrap it with `FittedBox`, it worked to me.
