### ISSUE TITLE
New Animations not actually added?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [jogboms/flutter_spinkit#34]
Hi, good to see more animations added! In checking with the 1.0 update and looking at the exports and the file, it doesn't look like the new animations made it to the file? I'm not able to find the new ones.
```
library flutter_spinkit;

export 'src/chasing_dots.dart';
export 'src/double_bounce.dart';
export 'src/fading_cube.dart';
export 'src/folding_cube.dart';
export 'src/pulse.dart';
export 'src/rotating_circle.dart';
export 'src/rotating_plain.dart';
export 'src/fading_four.dart';
export 'src/three_bounce.dart';
export 'src/wave.dart';
export 'src/circle.dart';
export 'src/fading_circle.dart';
export 'src/wandering_cubes.dart';
export 'src/cube_grid.dart';
export 'src/pumping_heart.dart';

```

I was looking for the DualRing

**Comment by jogboms** [comment]
@ThinkDigitalRepair try the 2.0 release.

**Comment by ThinkDigitalSoftware** [comment]
That must be it. I hit flutter packages upgrade. I thought that would do
it. I'll go ahead and change the dependencies in the pubspec.yaml file.
Thanks!

**Comment by ThinkDigitalSoftware** [comment]
Oh, on the pub page, the readme still shows 1.0, but the installing page shows 2.0

**Comment by ThinkDigitalSoftware** [comment]
Me again 😄 I keep getting the error:
```
I/flutter (14810): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter (14810): The following assertion was thrown resolving an image codec:
I/flutter (14810): Unable to load asset: packages/flutter_spinkit/assets/dual-ring.png
```
I checked in the pub cache folder, `/Users/thinkdigital/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_spinkit-2.0.0/lib/assets` and dual-ring.png exists.

**Comment by jogboms** [comment]
@ThinkDigitalRepair That's odd though. Maybe because v2.0.0 is still in `AWAITING` mode on pub. 
See https://github.com/jogboms/flutter_spinkit/blob/0cc8e3754c70e84b61f88a9ab31d31e48fdb9e1f/lib/flutter_spinkit.dart#L7

**Comment by ThinkDigitalSoftware** [comment]
It is

**Comment by jogboms** [comment]
Okay @ThinkDigitalRepair, i just tested out on a fresh project using `^2.0.0` and it works as expected.

**Comment by ThinkDigitalSoftware** [comment]
OK, I’ll keep troubleshooting. Thank you
