### ISSUE TITLE
Cannot customize the alignment, always in center screen

### ISSUE THREAD

**Issue by baoxiehao** [jogboms/flutter_spinkit#37]
SpinKitFadingCircle etc will only be shown in the middle of the screen.

As following code says that there is no alignment setting for the widget, and I check the source code that the alignment is default to center. And if I constraint the widget inside a container at the bottom of the screen, the widget will not be shown.

```dart
SpinKitFadingCircle(
  color: Colors.white,
  width: 50.0,
  height: 50.0,
);
```

Here is my code, which CircularProgressIndicator be replaced by SpinKitFadingCircle if I want to place it at the bottom.

```dart
  Widget _buildProgressIndicator() {
    return Container(
      alignment: Alignment.bottomCenter,
      padding: const EdgeInsets.all(16.0),
      child: Opacity(
        opacity: widget.isLoading ? 1.0 : 0.0,
        child: Container(
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: Colors.white,
          ),
          child: SizedBox(
            width: 40.0,
            height: 40.0,
            child: Container(
              padding: EdgeInsets.all(8.0),
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation(kShrinePink300),
                strokeWidth: 3.0,
              ),
            ),
          ),
        ),
      ),
    );
  }
```
Hope it makes more clear. Sorry for the detail missing. I thought it was quite a obvious problem.

**Comment by jogboms** [comment]
@baoxiehao 
Could you maybe try following this guide so i can understand you better?

**Describe the bug**
_A clear and concise description of what the bug is._

**SpinKit name**
_The name of the loader with which this bug occurred._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Comment by jogboms** [comment]
Sorry for the delay @baoxiehao, i didn't get a notification for an edited issue. 

Technically the SpinKit is just a square container with a customizable size. 

I figure if you want to align it anywhere on the screen, just put the SpinKit in a bounded container and then align that container anywhere you want it to be.

**Comment by baoxiehao** [comment]
Sure, I will try that out. I am new to Flutter. Thanks

**Comment by baoxiehao** [comment]
> Sure, I will try that out. I am new to Flutter. Thanks

Just add it to a column with bottomCenter alignment and it works.

**Comment by soonsam123** [comment]
This [SO answer](https://stackoverflow.com/a/45777468/8383332) worked for me:

```
return new Column(
  crossAxisAlignment: CrossAxisAlignment.center,
  mainAxisSize: MainAxisSize.max,
  mainAxisAlignment: MainAxisAlignment.end,
  children: <Widget>[
      SpinKitChasingDots(
                  color: Theme.of(context).accentColor, size: 35.0)),
  ],
);
```

**Comment by ershat-dl** [comment]
hi man, try wrap it with `FittedBox`, it worked to me.
