### ISSUE TITLE
Request for a speed argument

### ISSUE THREAD

**Issue by Tremx389** [jogboms/flutter_spinkit#43]
Please add an optional argument that can be used to specify the speed of the animation.
This can be extremely useful feature in UX customization, and shouldn't be more then a few lines of code.

**Comment by gsunit** [comment]
Why don't you try a PR?

**Comment by jogboms** [comment]
Thank you @Tremx389, It sure would be a worthy addition, due to how swamped work hours can get, do you mind laying out how you want this to go maybe in a PR as @gsunit suggested?
