### ISSUE TITLE
Some GIFs not loading on pub site

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [jogboms/flutter_spinkit#44]
**Describe the bug**
Probably nothing you can do about it, but just in case you weren't aware, some GIFs don't load on [pub.dartlang.org](pub.dartlang.org), but load on Github

**SpinKit name**
The name of the loader with which this bug occurred.

**Screenshots**
<img width="839" alt="screen shot 2018-10-13 at 9 19 42 pm" src="https://user-images.githubusercontent.com/23037821/46912573-ee1a9e80-cf2d-11e8-8870-5e8d75965005.png">

**Comment by jogboms** [comment]
Thanks @ThinkDigitalRepair  it has been fixed [here](https://github.com/jogboms/flutter_spinkit/commit/4f756b530c24434cdbd2d0fcafeaa214bb8b9e64) with but not published yet.
