### ISSUE TITLE
Refactor:  add mask when show loading

### ISSUE THREAD

**Issue by VesperHan** [jogboms/flutter_spinkit#50]
when show loading,  use can click button or other widgets,  actually user cannot touch in the loading. So i want to add mask. how to do it ?

**Describe the bug**

**SpinKit name**
The name of the loader with which this bug occurred.

**Screenshots**

**Comment by jogboms** [comment]
@VesperHan can you describe with a simple sketch or design what you wish to achieve?

**Comment by aagarwal1012** [comment]
@jogboms, 
Since there is no reply from @VesperHan, I am closing this issue. Feel free to reopen it if any problem exists.
