### ISSUE TITLE
[Request] Hope to expose AnimationController

### ISSUE THREAD

**Issue by peng8350** [jogboms/flutter_spinkit#51]
I have a requirement to control the playback and pause of animation, so I hope to provide a parameter to pass AnimationController, so that I can control when the animation is played and when it is paused.

**Comment by jogboms** [comment]
Can you please explain a little bit more? How exactly does the current implementation limit what you want to do and what can of change would help out.

**Comment by peng8350** [comment]
![gif9](https://user-images.githubusercontent.com/19425362/60353231-2b5f8780-99fc-11e9-8c05-d23934ef301a.gif)
As shown above, I want to achieve this effect: when the indicator enters the refresh state, it begins to call AnimationController. repeat () for animation loop effect. By looking at the source code, I found that the AnimationController for each indicator was encapsulated in its state and private. 

My solution is only copy one of your indicator,and update like this.
```
final AnimationController animationController;
SpinKitFadingCircle({
    Key key,
    this.color,
    this.size = 50.0,
    this.itemBuilder,
    this.animationController,
    this.duration = const Duration(milliseconds: 1200),
  })

@override
  void initState() {
    super.initState();

    _controller = widget.animationController ?? AnimationController(vsync: this, duration: widget.duration);
   // _controller.repeat();
  }

```

**Comment by jogboms** [comment]
Okay. This could work and won't introduce any breaking changes. If you don't mind, can you create a PR for this? I am a bit swamped with personal work at the moment.

Thanks!
