### ISSUE TITLE
Please give more detail about how to use in wiki.

### ISSUE THREAD

**Issue by haoyd** [jogboms/flutter_spinkit#58]
Developers need to check source code to find out how to show and hide If they want to use this component now, please give more details to make it easy.

**Comment by jogboms** [comment]
Hey @haoyd 

How do you mean? I believed it to be a self-contained component.

**Comment by haoyd** [comment]
> Hey @haoyd
> 
> How do you mean? I believed it to be a self-contained component.

I hope the component contains a function that can show and hide easily.

**Comment by jogboms** [comment]
Currently, none of the animations contains a mechanism to hide or show itself. Think of it as an Icon. What you choose to do with it is up to you. Use a boolean variable to act as a toggle is the simplest i can think of right now.
