### ISSUE TITLE
The method 'reverse' was called on null

### ISSUE THREAD

**Issue by magnuswikhog** [jogboms/flutter_spinkit#63]
**Describe the bug**
I'm getting the following exception

    The method 'reverse' was called on null

after the animation stops showing.

The stacktrace looks like this (and goes on and on like this for 500 lines):

	I/flutter (11044): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
	I/flutter (11044): The following NoSuchMethodError was thrown while notifying status listeners for AnimationController:
	I/flutter (11044): The method 'reverse' was called on null.
	I/flutter (11044): Receiver: null
	I/flutter (11044): Tried calling: reverse()
	I/flutter (11044): 
	I/flutter (11044): When the exception was thrown, this was the stack:
	I/flutter (11044): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
	I/flutter (11044): #1      autoReverseFn.<anonymous closure> (package:flutter_spinkit/src/utils.dart:8:27)
	I/flutter (11044): #2      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:193:19)
	I/flutter (11044): #3      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:753:7)
	I/flutter (11044): #4      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:585:7)
	I/flutter (11044): #5      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:458:12)
	I/flutter (11044): #6      _SpinKitCubeGridState.initState (package:flutter_spinkit/src/cube_grid.dart:37:9)
	I/flutter (11044): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
	I/flutter (11044): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
	I/flutter (11044): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
	I/flutter (11044): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
	I/flutter (11044): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
	I/flutter (11044): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
	I/flutter (11044): #13     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
	I/flutter (11044): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
	I/flutter (11044): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)

**SpinKit name**

SpinKitCubeGrid

**Screenshots**

**Comment by jogboms** [comment]
Hey @magnuswikhog 

What version are you on?

**Comment by magnuswikhog** [comment]
I was initially on version 4.0.0, but the same thing happens on version 4.1.0. My Flutter version is 1.9.1+hotfix.6, stable channel.

I've so far only seen it on Android emulators and devices.

**Comment by magnuswikhog** [comment]
This issue seems to appear when starting the animation "in reverse", i.e. 

    AnimationController(vsync: this, value: 1.0, lowerBound: 0.0, upperBound: 1.0, duration: const Duration(milliseconds: 800));

where `value` is `>= upperBound`. 

The problem seems to be that when assigning the `_controller` in `cube_grid.dart`, `autoReverseFn()` is called before `_controller` is actually assigned, causing the null pointer exception.

Changing 

    _controller = (widget.controller ?? AnimationController(vsync: this, duration: widget.duration))
      ..addStatusListener(autoReverseFn(() => _controller))
      ..forward();

to

    _controller = (widget.controller ?? AnimationController(vsync: this, duration: widget.duration));
    _controller
      ..addStatusListener(autoReverseFn(() => _controller))
      ..forward();

seems to resolve the issue. 

However, I noticed that there is a branch called `refactor/auto-revers` that uses 

    _controller = (widget.controller ?? AnimationController(vsync: this, duration: widget.duration))
      ..repeat(reverse: true);

instead, and this also seems to resolve the issue.

**Comment by jogboms** [comment]
Yes. Right. I actually plan to merge that and create a new release since flutter now supports auto-reverse natively. By the end of today, I'd publish a fix for it. Thanks
