### ISSUE TITLE
[Minor] Required constructor parameter for SpinKitWidgets 

### ISSUE THREAD

**Issue by md-weber** [jogboms/flutter_spinkit#66]
To help the users, we should maybe think about to add a required parameter for the Widgets that need, for example, colour. That would help them directly in the editor instead of throwing only a red screen.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/8026644/71107668-d722ac80-21c1-11ea-8bba-db995ee993b1.png">

In the Image, you can see what I mean for the colour of the SpinKitFadingCircle. This is a minor improvement.

This is only a problem if there is no const in front of the class name. E.g.
![image](https://user-images.githubusercontent.com/8026644/71115108-81560080-21d1-11ea-9066-f9db30da9109.png)

**Comment by jogboms** [comment]
Hey @md-weber 

There is currently no way to do this without using asserts as `color` only becomes required when `itemBuilder` is not and vice versa.
