### ISSUE TITLE
Flare animation support?

### ISSUE THREAD

**Issue by hanabi1224** [jogboms/flutter_spinkit#67]
Flare provides powerful toolset to create animations and efficient runtime: https://github.com/2d-inc/Flare-Flutter  Flare animation has stable 60fps which looks much better than GIFs.  Some [examples](https://github.com/nb312/flutter-animations)

**Comment by jogboms** [comment]
Hey @hanabi1224 
I really do not understand what you mean, this library does not use GIFs.

**Comment by hanabi1224** [comment]
@jogboms Sorry, then never mind : )
