### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by nslogx** [jogboms/flutter_spinkit#68]
https://pub.dev/packages/flutter_easyloading

<img src="https://raw.githubusercontent.com/huangjianke/flutter_easyloading/master/images/gif01.gif" width=250 height=535/> <img src="https://raw.githubusercontent.com/huangjianke/flutter_easyloading/master/images/gif02.gif" width=250 height=535/> <img src="https://raw.githubusercontent.com/huangjianke/flutter_easyloading/master/images/gif03.gif" width=250 height=535/>

**Comment by jogboms** [comment]
Hey @huangjianke 

This is good stuff. Thanks for sharing. 💙
