### ISSUE TITLE
Animations always center inside TextFields and obscure the text

### ISSUE THREAD

**Issue by TonchoZhelev** [jogboms/flutter_spinkit#69]
I'm trying to use one of the animations as a prefixIcon inside an InputDecoration inside a TextField,
however instead of the animation sitting to the left it centers itself over the text inside the TextField and obscures all the text no matter how long it is.

I've tested this with the properties prefix, prefixIcon, suffix and suffixIcon, and I've tested many of the animations, every one of the ones i tested exhibits the bug with the exception of SpinKitCubeGrid.

![spinkit_bug](https://user-images.githubusercontent.com/16443493/72542314-9be0cf80-388c-11ea-85e6-d98d8ca7fdd7.png)

Here is code with which i tested:
```
class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: <Widget>[
          TextField(
            decoration: InputDecoration(
              prefixIcon: SpinKitCircle(
                color: Colors.blue,
              ),
            ),
          ),
        ],
      ),
    );
  }
```

**Comment by jogboms** [comment]
Hey @PifeVoxd, Took a long time but I believe you can just constrain the kit in an aligned box

**Comment by ershat-dl** [comment]
hi man, try wrap it with `FittedBox`, it worked to me.
