### ISSUE TITLE
Animation not working properly

### ISSUE THREAD

**Issue by JuanM04** [jogboms/flutter_spinkit#70]
**Describe the bug**
You can see it. I'm using API level 29 and Flutter 1.12

**SpinKit name**
WanderingCubes (but also happend DoubleBounce, so maybe happens with all SpinKits)

**Screenshots**
(Ignore the speed -- recording issues)
![spinkit.gif](https://user-images.githubusercontent.com/16712703/72723401-59a2e100-3b5f-11ea-85c9-e33f6b4e8745.gif)

**Comment by jogboms** [comment]
Thanks for pointing this point. Turns out during the rewrite, a couple of bugs was created within the maths. For this kit, it does work as expected

**Comment by jogboms** [comment]
Hey @JuanM04 
The fix was just released in v4.1.2

**Comment by JuanM04** [comment]
DoubleBounce was fixed (thanks!), but WanderingCubes no
