### ISSUE TITLE
Feature request: custom icon as input for progress indicator

### ISSUE THREAD

**Issue by giorgio79** [jogboms/flutter_spinkit#76]
Hello,

I would like my icon to be displayed as a rotating progress indicator. Any plans to allow for an "Icon" or "Image" input, that is then used as the item to animate as the indicator?
**Describe the bug**

**SpinKit name**
The name of the loader with which this bug occurred.

**Screenshots**

**Comment by jogboms** [comment]
Hey

Isn’t the `itemBuilder` property sufficient for this purpose?

**Comment by heberhenrique** [comment]
> Hey
> 
> Isn’t the `itemBuilder` property sufficient for this purpose?

Do you have some example that how i can use itemBuilder?

**Comment by jogboms** [comment]
Hey @heberhenrique 

Here https://github.com/jogboms/flutter_spinkit#-how-to-use
