### ISSUE TITLE
Lags with package: password: ^1.0.0

### ISSUE THREAD

**Issue by zuwuko** [jogboms/flutter_spinkit#77]
I'm using this spinkit animation while authenticating a user/pass with SQLITE local database that uses password hash to verify user input password (https://pub.dev/packages/password) and its super slow and freezes/lags the spinkit animation.
Ideas?

**Comment by jogboms** [comment]
Hey @zuwuko 

I cannot say for sure how it relates but could you maybe use the hashing algorithm within an `isolate`? Use the `compute` function so it maybe run in a different process.
