### ISSUE TITLE
SpinKitCubeGrid not working as showcased

### ISSUE THREAD

**Issue by williamgaoyuan** [jogboms/flutter_spinkit#80]
SpinKitCubeGrid plays a back-and-forth animation, with the cubes disappearing from bottom left and then reappearing from top right, instead of reappearing from bottom left as the gif in README.md shows.

**Comment by AleixFerre** [comment]
Same issue with me.
Flutter version: `1.21.0-9.1.pre`

**Comment by TheLastGimbus** [comment]
Yup, same for me, with `CubeGrid` and `FoldingCube`

**Comment by jogboms** [comment]
Hey @williamgaoyuan @AleixFerre @TheLastGimbus 
Can you check if https://github.com/jogboms/flutter_spinkit/pull/99 solves the issue for you?

**Comment by jogboms** [comment]
Closed by #120
