### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Overman775** [jogboms/flutter_spinkit#85]
Hi! thanks for package. Can you publish null-safety to prerelease in pub.dev like other packages? Thanks )

**Comment by alexodus** [comment]
+1

**Comment by walsha2** [comment]
Are there any plans for this? No rush, but would just like to plan accordingly!

@jogboms @aagarwal1012 I also noticed that there have not been any commits in almost a year. Is this package still actively maintained?

**Comment by gabrielginter** [comment]
+1 flutter 2.0 was released hours ago, I guess we are all excited to migrate :)

**Comment by chavesgu** [comment]
+1

**Comment by jogboms** [comment]
Its coming right up!

**Comment by gabrielginter** [comment]
literally right up! 🤣

you rock
