### ISSUE TITLE
both FoldingCube & CubeGrid animation are incorrect

### ISSUE THREAD

**Issue by sooxt98** [jogboms/flutter_spinkit#91]
https://raw.githubusercontent.com/ybq/AndroidSpinKit/master/art/FoldingCube.gif
https://raw.githubusercontent.com/ybq/AndroidSpinKit/master/art/CubeGrid.gif

The animation doesn't match with the demo, appears to be looping or reverse backward when animation ends

**Comment by tanzilzubair** [comment]
I have the same problem

**Comment by jogboms** [comment]
Hey @sooxt98 
Can you check if https://github.com/jogboms/flutter_spinkit/pull/99 solves the issue for you?

**Comment by jogboms** [comment]
Closed in favour of #80
