### ISSUE TITLE
PouringHourGlass or PouringHourglass ?

### ISSUE THREAD

**Issue by hardiklakhalani** [jogboms/flutter_spinkit#93]
**Describe the bug**
Showcase on [https://pub.dev/packages/flutter_spinkit] shows **PouringHourGlass**  to call spinner but it's coded by `PouringHourglass`

**SpinKit name**
PouringHourGlass 

**Screenshots**
![image](https://user-images.githubusercontent.com/82162165/115069518-4a047a80-9f11-11eb-8fd7-cb784f6ea005.png)

![image](https://user-images.githubusercontent.com/82162165/115069702-98b21480-9f11-11eb-85c7-b847e0c1423a.png)

**Comment by Mohdx** [comment]
Its also so thick 😨

**Comment by jogboms** [comment]
PRs are most welcomed here too. 🙏

**Comment by jogboms** [comment]
Closed with #101
