### ISSUE TITLE
Don't Support null safety

### ISSUE THREAD

**Issue by harshkumarkhatri** [jogboms/flutter_spinkit#96]
**Describe the bug**
I was trying to add the package and use it in my flutter app but every time I ran the app it showed me this error in it.

**SpinKit name**
The name of the loader with which this bug occurred.

**Screenshots**
![image](https://user-images.githubusercontent.com/42743629/123907969-5c307980-d994-11eb-8312-940293a91a94.png)

**Comment by jonmountjoy** [comment]
You didn't specify what version you're using.  "5.0.0" has null safety.

**Comment by jogboms** [comment]
Null safe support landed in v5.0. https://github.com/jogboms/flutter_spinkit/releases/tag/v5.0.0
